### ISSUE TITLE
name the enter skip message

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/MaxPhisher#10]
Hi bro, in option 6 <ip tracker> you forgot to put the message of [press enter to skip]: for beginners

**Comment by KasRoudra** [comment]
@Darkrevengehack Did you mean this?

![Screenshot_2022-10-17-23-19-48](https://user-images.githubusercontent.com/78908440/196243966-f629990b-d6ae-4ed3-ae5b-97e3513dda8b.jpeg)
