### ISSUE TITLE
unable to install maxphisher

### ISSUE THREAD

**Issue by naimurhossain** [KasRoudra/MaxPhisher#100]
![Screenshot_2023-09-19_02_04_42](https://github.com/KasRoudra/MaxPhisher/assets/143959186/e0c63003-e4b0-4ee6-afb9-537a2a0e6efe)
![Screenshot_2023-09-19_02_04_58](https://github.com/KasRoudra/MaxPhisher/assets/143959186/d4a7eecf-80c6-4025-9921-674bf396035c)
![Screenshot_2023-09-19_02_05_08](https://github.com/KasRoudra/MaxPhisher/assets/143959186/cb846983-e2c6-42b7-a4eb-c06885187ee5)

**Comment by KasRoudra** [comment]
@naimurhossain Closing this due to duplication. Discuss in other one
