### ISSUE TITLE
Instagram Messenger and FB Messenger detect links. 

### ISSUE THREAD

**Issue by SpoofytheWhale** [KasRoudra/MaxPhisher#101]
The links are being detected by Insta and FB and wont send. Maybe my account got flagged?  😅

**Comment by SpoofytheWhale** [comment]
And text too?  Link open up fine on my end

**Comment by KasRoudra** [comment]
@SpoofytheWhale How would you send the the link that's up to you. The urls are created by third party services which have separate owners. This issue should refer to them
