### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by FrigidTM** [KasRoudra/MaxPhisher#116]
File "maxphisher.py",  line 1062
   if (shortened:=shortener1(url)) != "":

SyntaxError: invalid syntax

**Comment by KasRoudra** [comment]
@FrigidTM Minimum python version to run this is 3.9. Your one is lower than 3.8

**Comment by FrigidTM** [comment]
my bad the main issue was using a very outdated version of linux im upgrading to hopefully avoid more simple issues like this
