### ISSUE TITLE
How to add custom website page?

### ISSUE THREAD

**Issue by dottorgiven** [KasRoudra/MaxPhisher#12]
Hello, I want to add a custom website page, I added all the php (validate,ip,login,meta) file in the folder with the index of the website page I want (renamed login.html.php) I found the IP victim but not the credentials. Why?

**Comment by dottorgiven** [comment]
I also added to the bottom of the index.hml code I included validate.php

**Comment by KasRoudra** [comment]
@dottorgiven Possible reasons
1. Your frontend content has some javascript that prevents submitting data to target php page
2. Your php page values do not match with html form values
3. Your php file do not point to `usernames.txt` to save credentials

**Comment by dottorgiven** [comment]
Thank you for yuour answer! The index of the website I want to clone does not contain any form action and login php, I think It works with javascript. The site is unable to clone also with the tool SET. Can you help me please? I used your php files

**Comment by KasRoudra** [comment]
@dottorgiven Unfortunately, I do not build phishing pages anymore. You've to do it on your own or you may hire some freelancer to get your job done
