### ISSUE TITLE
Custom Url 

### ISSUE THREAD

**Issue by Comrad30** [KasRoudra/MaxPhisher#13]
Please Remove This Customs Url Options,its Getting instant Block by Facebook (Cloudsfare) link also.

Btw @is.gd Working Fine 

Add This Custom Url Maker Please.

**Comment by KasRoudra** [comment]
@Comrad30 Run `git pull` and then try Maxphisher again

**Comment by Comrad30** [comment]
Its Working Now Thanks 🖤🖤
