### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mikeyxken2** [KasRoudra/MaxPhisher#14]
![AFABDCC2-8A18-4E49-A608-37B7DD3FC27E](https://user-images.githubusercontent.com/117107477/199347880-58f3a82e-ea9e-4ddc-88e6-51e7cc244e98.png)
Can somebody help me? I get this error every time. Also reinstalling doesnt help.

**Comment by KasRoudra** [comment]
Duplicate issue in PyPhisher
