### ISSUE TITLE
Erro when running maxphisher

### ISSUE THREAD

**Issue by LupinArssenejjj** [KasRoudra/MaxPhisher#16]
PermissionError: [Errno 13] Permission denied: '/sdcard/Media'

**Comment by KasRoudra** [comment]
@LupinArssenejjj You haven't allowed storage permission when it asked. Run
`termux-setup-storage` and press ok in popup

**Comment by LupinArssenejjj** [comment]
Tysm

Em qua, 23 de nov de 2022 02:47, KasRoudra ***@***.***>
escreveu:
