### ISSUE TITLE
about rsa key pair

### ISSUE THREAD

**Issue by SHUBHUzzz** [KasRoudra/MaxPhisher#17]
asking for file name to save key?? about rsa key public/private

**Comment by KasRoudra** [comment]
@SHUBHUzzz Press enter three times

**Comment by SHUBHUzzz** [comment]
thanks for that now when i use image link than where those images are getting save ??

**Comment by KasRoudra** [comment]
@SHUBHUzzz For termux `/sdcard/Media`, for linux `$HOME/Media`

**Comment by SHUBHUzzz** [comment]
got it but where i can saw those images its not showing in my phone

**Comment by KasRoudra** [comment]
@SHUBHUzzz Check the mentioned folder in file manager

**Comment by SHUBHUzzz** [comment]
it show access denied in file manager how to get access any idea

**Comment by KasRoudra** [comment]
@SHUBHUzzz Send a screenshot

**Comment by SHUBHUzzz** [comment]
![Screenshot_2022-11-25-08-09-17-20_a61e42d1eea86d28f403f78330ec114d](https://user-images.githubusercontent.com/118967989/203889529-16ebafe2-f80f-4ebe-b064-9ecf9adcdf30.jpg)
see this , in android 11 we don't have access to app data through phone's file manager tso i use another manager and it show access denied

**Comment by KasRoudra** [comment]
@SHUBHUzzz Where have I said to go there? If files are collected, they are in `/sdcard/Media`. Check that folder

**Comment by SHUBHUzzz** [comment]
There is no location of this name

**Comment by KasRoudra** [comment]
@SHUBHUzzz Try `/storage/emulated/0/Media`
