### ISSUE TITLE
problems with python3 MaxPisher.py

### ISSUE THREAD

**Issue by LupinArssenejjj** [KasRoudra/MaxPhisher#18]
templates.json file is corrupted!

**Comment by KasRoudra** [comment]
@LupinArssenejjj Run `rm -rf ~/.maxsites` and then start maxphisher again

**Comment by LupinArssenejjj** [comment]
Can you help me? Is it possible to download Linux on Android 32 bits?

**Comment by KasRoudra** [comment]
@LupinArssenejjj Irrelevant, I don't know about that

**Comment by busterbeam** [comment]
@LupinArssenejjj this repo suggests you use termnux app to start a subprocess to allow to do basic terminal based work. I suggest you look into AOSP-Exposed, postmarketOS or Mobian for android alternatives that allow more direct access to hardware.  Android is on Linux but it doesn't fit with the Linux philosophy (certainly not GNU).
