### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by sofiaremanpour** [KasRoudra/MaxPhisher#19]
Hi im fairly new to this but this is the error I'm getting when I run maxphisher. 
<img width="812" alt="Screen Shot 2022-11-29 at 4 07 50 PM" src="https://user-images.githubusercontent.com/117949935/204647857-b1ae3941-7c17-459d-bffa-83bdf4643ea9.png">

Pls can you help

**Comment by KasRoudra** [comment]
@sofiaremanpour Mac users are requested to use docker
