### ISSUE TITLE
How to change raedy template pages?

### ISSUE THREAD

**Issue by goozdy** [KasRoudra/MaxPhisher#2]
Hi. How to change ready template pages? Because part of them old!

**Comment by KasRoudra** [comment]
@goozdy You need to know some web development for this. Then you can edit the files of `~/.maxsites` to change template pages

**Comment by goozdy** [comment]
@KasRoudra I tryed to make custom page, but I can't make own  telegram phishing page. Where ~/.maxsites located? There are only 
/home/kali/Desktop/programmes/MaxPhisher/files/changelog.log
/home/kali/Desktop/programmes/MaxPhisher/files/Dockerfile
/home/kali/Desktop/programmes/MaxPhisher/files/email.json
/home/kali/Desktop/programmes/MaxPhisher/files/MANIFEST.in
/home/kali/Desktop/programmes/MaxPhisher/files/maxphisher.gif
/home/kali/Desktop/programmes/MaxPhisher/files/requirements.txt
/home/kali/Desktop/programmes/MaxPhisher/files/setup.py
/home/kali/Desktop/programmes/MaxPhisher/files/version.txt
this files. @KasRoudra if you have sometime can you explain where exactly  located. I want just to change colors, add one more page, page of two-factor authentication. Thank you!

**Comment by KasRoudra** [comment]
@goozdy I think the files are here `/home/kali/.maxsites`. If it doesn't work try `$HOME/.maxsites`

**Comment by goozdy** [comment]
@KasRoudra thank you Mr.Developer :+1: I searched it 3-4 days
