### ISSUE TITLE
Some pages do not load images (like instagram template)

### ISSUE THREAD

**Issue by tommeuh** [KasRoudra/MaxPhisher#23]
Hello ! 
I'm opening a post because I see that some images are not loading with Maxphisher. For example, when I create an Instagram page, there are no images. Do you know why ? Most templates work fine. thank you for your work
![maxphisher](https://user-images.githubusercontent.com/72951217/208251134-578e4b2b-ba19-4ba9-b9be-e1ad2c7b62a0.jpg)

**Comment by KasRoudra** [comment]
@tommeuh Thanks for your feedback. That happens when pages are outdated. I'll try to update them soon. You may mention all the templates you've faced issues

**Comment by KasRoudra** [comment]
@tommeuh Your issue isn't reproducible. Maybe this is caused due to your internet interruption

![Screenshot_2023-01-02-18-01-30](https://user-images.githubusercontent.com/78908440/210228760-d7979c90-89d5-4531-ad58-4a5c557f0b97.jpeg)
