### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kamo-Meloyan** [KasRoudra/MaxPhisher#24]
Tunneling failed! Use your own tunneling service on port 8080!

**Comment by KasRoudra** [comment]
@Kamo-Meloyan Add a screenshot

**Comment by Kamo-Meloyan** [comment]
![Screenshot_20221225_190456_Termux](https://user-images.githubusercontent.com/76214445/209473065-6c63c8a4-dfbc-4f94-8278-0e14b1114548.jpg)

**Comment by KasRoudra** [comment]
@Kamo-Meloyan Turn on hotspot and try again

**Comment by nickfour** [comment]
![Screenshot_2022-12-28-20-08-30-64_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/105587657/209817374-f924ccf0-259b-4990-8063-d0f98dc0a36a.jpg)
