### ISSUE TITLE
Error helppp

### ISSUE THREAD

**Issue by nickfour** [KasRoudra/MaxPhisher#25]
![Screenshot_2022-12-28-20-08-30-64_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/105587657/209817536-7febaf87-021a-481c-a79d-84de17cdb725.jpg)

**Comment by KasRoudra** [comment]
@nickfour You haven't allowed storage permission. Now run `termux-setup-storage`, allow that and start maxphisher
