### ISSUE TITLE
Why is the clipboard not working?

### ISSUE THREAD

**Issue by nickfour** [KasRoudra/MaxPhisher#26]
![Screenshot_2022-12-29-08-28-38-74_f9ee0578fe1cc94de7482bd41accb329.jpg](https://user-images.githubusercontent.com/105587657/209891968-29b2ede2-515e-44e8-bfab-d3c9aa7ec5e4.jpg)

**Comment by KasRoudra** [comment]
@nickfour It will ask victim permission in browser. Victim browser should have that support and allow that too
