### ISSUE TITLE
All links are already detected as phishing websites

### ISSUE THREAD

**Issue by Rohanaaaaa** [KasRoudra/MaxPhisher#30]
I tried the Instagram page and though it works great afterwards, a phishing site warning is shown when the link is visited. Any option to bypass this? 
No one will visit the page and enter their credentials if it's already reported as a phishing site.

**Comment by Jhoab2916** [comment]
Todos los links se detectan ya como phishing
Alguna solución?

**Comment by KasRoudra** [comment]
To remove ngrok preload page you may buy a ngrok subsciption. We have no control over port forwarding services, those issues refer to them
