### ISSUE TITLE
error how to fix

### ISSUE THREAD

**Issue by mocha69420** [KasRoudra/MaxPhisher#35]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mocha/MaxPhisher/maxphisher.py:1562 in <module>                                            │
│                                                                                                  │
│   1559                                                                                           │
│   1560 if __name__ == '__main__':                                                                │
│   1561 │   try:                                                                                  │
│ ❱ 1562 │   │   main_menu()                                                                       │
│   1563 │   except KeyboardInterrupt:                                                             │
│   1564 │   │   pexit()                                                                           │
│   1565 │   except Exception as e:                                                                │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:1303 in main_menu                                           │
│                                                                                                  │
│   1300 │   │   if choice in choices:                                                             │
│   1301 │   │   │   index = choices.index(choice)                                                 │
│   1302 │   │   │   phishing_type = names[index]                                                  │
│ ❱ 1303 │   │   │   secondary_menu(templates[phishing_type], phishing_type)                       │
│   1304 │   │   elif choice.lower()=="a":                                                         │
│   1305 │   │   │   about()                                                                       │
│   1306 │   │   elif choice.lower()=="s":                                                         │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:1390 in secondary_menu                                      │
│                                                                                                  │
│   1387 │   │   │   set_duration()                                                                │
│   1388 │   │   if name in ["Location", "IP Tracker", "Device"]:                                  │
│   1389 │   │   │   set_redirect(redir_url)                                                       │
│ ❱ 1390 │   server()                                                                              │
│   1391                                                                                           │
│   1392 # Start server and tunneling                                                              │
│   1393 def server():                                                                             │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:1496 in server                                              │
│                                                                                                  │
│   1493 │   │   sprint(f"\n{error}Tunneling failed! Use your own tunneling service on port {port  │
│   1494 │   │   if mode == "test":                                                                │
│   1495 │   │   │   exit(1)                                                                       │
│ ❱ 1496 │   waiter()                                                                              │
│   1497                                                                                           │
│   1498 # Last function capturing credentials                                                     │
│   1499 def waiter():                                                                             │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:1511 in waiter                                              │
│                                                                                                  │
│   1508 │   │   │   │   print(f"\n\n{success}{bgreen}Victim IP found!\n\007")                     │
│   1509 │   │   │   │   show_file_data(ip_file)                                                   │
│   1510 │   │   │   │   ipdata = cat(ip_file)                                                     │
│ ❱ 1511 │   │   │   │   append(ipdata, main_ip)                                                   │
│   1512 │   │   │   │   # Just add the ip                                                         │
│   1513 │   │   │   │   append(ipdata.split("\n")[0], saved_file)                                 │
│   1514 │   │   │   │   print(f"\n{info2}Saved in {main_ip}")                                     │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:435 in append                                               │
│                                                                                                  │
│    432                                                                                           │
│    433 # Write/Append texts to a file                                                            │
│    434 def append(text, filename):                                                               │
│ ❱  435 │   with open(filename, "a") as file:                                                     │
│    436 │   │   file.write(str(text)+"\n")                                                        │
│    437                                                                                           │
│    438                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 13] Permission denied: 'ip.txt'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mocha/MaxPhisher/maxphisher.py:1566 in <module>                                            │
│                                                                                                  │
│   1563 │   except KeyboardInterrupt:                                                             │
│   1564 │   │   pexit()                                                                           │
│   1565 │   except Exception as e:                                                                │
│ ❱ 1566 │   │   exception_handler(e)                                                              │
│   1567                                                                                           │
│   1568 # If this code helped you, consider staring repository. Your stars encourage me a lot!    │
│   1569                                                                                           │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:573 in exception_handler                                    │
│                                                                                                  │
│    570 │   │   │   lines_arr.append(str(tb.tb_lineno))                                           │
│    571 │   │   tb = tb.tb_next                                                                   │
│    572 │   name = type(e).__name__                                                               │
│ ❱  573 │   append(e, error_file)                                                                 │
│    574 │   if ":" in str(e):                                                                     │
│    575 │   │   message = str(e).split(":")[0]                                                    │
│    576 │   elif "(" in str(e):                                                                   │
│                                                                                                  │
│ /home/mocha/MaxPhisher/maxphisher.py:435 in append                                               │
│                                                                                                  │
│    432                                                                                           │
│    433 # Write/Append texts to a file                                                            │
│    434 def append(text, filename):                                                               │
│ ❱  435 │   with open(filename, "a") as file:                                                     │
│    436 │   │   file.write(str(text)+"\n")                                                        │
│    437                                                                                           │
│    438                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 13] Permission denied: 'error.log'

![Screenshot 2023-02-21 122142](https://user-images.githubusercontent.com/125944755/220247402-5bc6d4d3-a729-4af6-8ef6-e821e7a9ffa5.png)
![222](https://user-images.githubusercontent.com/125944755/220247450-b0f1a424-d66c-4613-881d-0f0be0a7ee4b.png)

**Comment by mocha69420** [comment]
![image](https://user-images.githubusercontent.com/125944755/220247592-1d317ee0-8366-4880-8af3-681d9ceb4cfd.png)

**Comment by KasRoudra** [comment]
@mocha69420 Your os/distro?

**Comment by mocha69420** [comment]
nvm fixed it
