### ISSUE TITLE
A-Shell on Ios 

### ISSUE THREAD

**Issue by theotaku3261** [KasRoudra/MaxPhisher#38]
I’ve tried pip3 install phisher it installed but when i run maxphisher it gives me this 

───── Traceback (most recent call last) ───────╮
│ /var/mobile/Containers/Data/Application/B3B8C8 │
│ 9E-CD9A-4F36-B7DE-D109046328D6/Library/bin/max │
│ phisher:298 in <module>                        │
│                                                │
│    295 else:                                   │
│    296 │   default_dir = f"{home}/Media"       │
│    297 if not isdir(default_dir):              │
│ ❱  298    mkdir(default_dir)                   │
│    299                                         │
│    300 argparser = ArgumentParser()            │
│    301                                         │
╰────────────────────────────────────────────────╯
PermissionError: [Errno 1] Operation not 
permitted: 
'/private/var/mobile/Containers/Data/Application/B
3B8C89E-CD9A-4F36-B7DE-D109046328D6/Media'
[Documents]$ 

Im using A-Shell on Iphone 11 Ios 15.2

**Comment by KasRoudra** [comment]
@theotaku3261 It's a terminal permission issue of iphone. Not related to maxphisher. Android/linux are suggested to run maxphisher
