### ISSUE TITLE
Re install maxphisher

### ISSUE THREAD

**Issue by gaurav-beri** [KasRoudra/MaxPhisher#39]
How to uninstall or remove maxphisher tool fully .
i.e i am try to reinstall but didn't know how to remove it first

**Comment by KasRoudra** [comment]
@gaurav-beri What commands did you use to install it?

**Comment by gaurav-beri** [comment]
I have copy the source code and simply git clone the tool in Parrot OS.
After that in tool directory . i run python3 setup.py and install requirements with pip.
Thats it.

**Comment by KasRoudra** [comment]
@gaurav-beri Remove that directory. And the requirements are not relavant in reinstalling maxphisher. You may keep that

**Comment by gaurav-beri** [comment]
Ok thanks.
