### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mokkabca** [KasRoudra/MaxPhisher#4]
![image](https://user-images.githubusercontent.com/95523018/193446892-a66e9009-433d-4030-a414-cf4e82e30664.png)
 Already python is upto-date

**Comment by KasRoudra** [comment]
@mokkabca What is the python version?

**Comment by peric0** [comment]
+1 Python 3.9.2, Parrot 5.1

**Comment by KasRoudra** [comment]
@peric0 Python latest version is 3.10.7. At least upgrade to python 3.10.0 to use MaxPhisher

**Comment by mokkabca** [comment]
Thank you, after updating Python, it's working perfectly.
