### ISSUE TITLE
[!] OSError: [Errno 22] Invalid argument at lines 1562, 1303, 1390, 1404

### ISSUE THREAD

**Issue by hemialj** [KasRoudra/MaxPhisher#40]
I go this error what should I do [!] OSError: [Errno 22] Invalid argument at lines 1562, 1303, 1390, 1404

**Comment by KasRoudra** [comment]
@hemialj Isn't it mac?

**Comment by hemialj** [comment]
Yes

**Comment by KasRoudra** [comment]
@hemialj The terminal permission issue is not relavant to maxphisher. Use docker or virtual machine to run it
