### ISSUE TITLE
Erro no codigo termux android nao sou progamador nao entendo muito ainda 

### ISSUE THREAD

**Issue by Vinix-twz** [KasRoudra/MaxPhisher#45]
O termux esta indicando um erro no código na linha 297 segue o anexo 
![Screenshot_20230316_004126_Termux](https://user-images.githubusercontent.com/128013997/225508520-bda5ef85-c4e8-468b-9d9f-2f5c34d589a1.jpg)

**Comment by KasRoudra** [comment]
@Vinix-twz Termux from play store is not supported. Install from fdroid or github

**Comment by Vinix-twz** [comment]
Onde baixo o termux

Em qui., 16 de mar. de 2023 1:48 AM, KasRoudra ***@***.***>
escreveu:

**Comment by Vinix-twz** [comment]
Instalei o apk oficial e msm assim continuar dando o mesmo erro

Em qui., 16 de mar. de 2023 2:05 AM, Vinny Soares ***@***.***>
escreveu:

**Comment by KasRoudra** [comment]
@Vinix-twz Run `termux-setup-storage` and allow permission

**Comment by KasRoudra** [comment]
@Vinix-twz Irrelavant. Ask about maxphisher only
