### ISSUE TITLE
Can't Use With Wifi

### ISSUE THREAD

**Issue by Abhimanyu2008** [KasRoudra/MaxPhisher#47]
The Script Is Not working with wifi , someone using wifi can't access the link.

**Comment by KasRoudra** [comment]
@Abhimanyu2008 Irreproducible. How many wifi have you tried?

**Comment by Abhimanyu2008** [comment]
> @Abhimanyu2008 Irreproducible. How many wifi have you tried?

**Comment by Abhimanyu2008** [comment]
> > @Abhimanyu2008 Irreproducible. How many wifi have you tried?

I've Tried It On My Friends (I Told Them About It Before) , So , As I'm From Chattogram, Bangladesh..2 Of My Friends Use The Wifi Provider - Chattogram Online Limited (COL BD) , And When I Sent The Link To Them , They Clicked On It And Is Was Showing "This Site Can't Be Reached" , But I Was Getting Their IP Address , Mobile Specifications etc etc...But They Were Unable To Use The Login Page , But I Tried It With My 3rd Friend Who Uses Grammenphone Sim , I Was Able To Get His Id And Password..
So , Is This A Problem With The Network Provider Or Something Else ?

**Comment by Abhimanyu2008** [comment]
> @Abhimanyu2008 Irreproducible. How many wifi have you tried?

I've Tried It On My Friends (I Told Them About It Before) , So , As I'm From Chattogram, Bangladesh..2 Of My Friends Use The Wifi Provider - Chattogram Online Limited (COL BD) , And When I Sent The Link To Them , They Clicked On It And Is Was Showing "This Site Can't Be Reached" , But I Was Getting Their IP Address , Mobile Specifications etc etc...But They Were Unable To Use The Login Page , But I Tried It With My 3rd Friend Who Uses Grammenphone Sim , I Was Able To Get His Id And Password..
So , Is This A Problem With The Network Provider Or Something Else ?

**Comment by Abhimanyu2008** [comment]
> @Abhimanyu2008 Irreproducible. How many wifi have you tried? @KasRoudra 
I've Tried It On My Friends (I Told Them About It Before) , So , As I'm From Chattogram, Bangladesh..2 Of My Friends Use The Wifi Provider - Chattogram Online Limited (COL BD) , And When I Sent The Link To Them , They Clicked On It And Is Was Showing "This Site Can't Be Reached" , But I Was Getting Their IP Address , Mobile Specifications etc etc...But They Were Unable To Use The Login Page , But I Tried It With My 3rd Friend Who Uses Grammenphone Sim , I Was Able To Get His Id And Password..
So , Is This A Problem With The Network Provider Or Something Else ?

**Comment by KasRoudra** [comment]
@Abhimanyu2008 Test against some more wifi providers and send error screenshot. This can be an issue of specific wifi provider
1. Did all links(ngrok, cloudflared, localhostrun) show this error? 
2. Which option caused this issue?
