### ISSUE TITLE
How to use Maxpisher with own Domain?

### ISSUE THREAD

**Issue by Gehmalbierholen123e** [KasRoudra/MaxPhisher#49]
Hello,
I tried Maxpisher and it works good. Just one thing, how can I use this with my own Domain? I want the pishing links (f.e. login) to go over my domain. How do I do this?

Thanks in advance!

**Comment by KasRoudra** [comment]
@Gehmalbierholen123e currently it is not possible natively. If your domain provider gives you a way to connect a domain to your certain port (8080 for maxphished) you can try that
