### ISSUE TITLE
How does the Cam-Phishing work??

### ISSUE THREAD

**Issue by Gehmalbierholen123e** [KasRoudra/MaxPhisher#50]
Hi,
I tried Cam-Phishing with MaxPisher but I can't get it to work??
I tried the "Video" option, but all it did was give me the ip and all that but no video.
I also tried vidphisher (seperate git) but didn't worked neither.
How do I do this? Am I missing something??

Thanks in advance!

**Comment by KasRoudra** [comment]
@Gehmalbierholen123e Both of them works in sane way. If one doesn't work, other won't. However, in which browser did you try? Have you allowed camera permission?
