### ISSUE TITLE
I am getting error after while python3 pyphisher.py

### ISSUE THREAD

**Issue by harish883871** [KasRoudra/MaxPhisher#51]
When i run python3 pyphisher.py ,i am getting the below error
And my internet connection is working fine 
[!] Download failed due to: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max r
tries exceeded with url: /KasRoudra/files/main/ngrok/ngrok-v3-stable-linux-amd64.tgz (Caused by N
ewConnectionError(*<urllib3.connection.HTTPSConnection object at 0x7f68ece410f0>: Failed to establ
ish a new connection: [Errno 101] Network is unreachable"))

<img width="1177" alt="227783506-3b2ce27d-4c77-4259-b374-9583d532608c" src="https://user-images.githubusercontent.com/129325581/228716269-bcb9b9d3-6572-4dff-b5e4-62c498f95368.png">

**Comment by busterbeam** [comment]
The problem is, githubusercontent.com isn't KasRoudra's domain, but he is trying to use it for his own "package manager".
