### ISSUE TITLE
The links generated give a error in cloudflare

### ISSUE THREAD

**Issue by Aryancoder9191** [KasRoudra/MaxPhisher#52]
I am using chrome browser and running the maxphisher program in my mobile.I have tried the vidphisher and link phisher but both give the same error of cloudflare and ngrok , it says there is some problem with the tunnelers , i didnt used my own key of ngrok and localx, any solutions?

**Comment by KasRoudra** [comment]
@Aryancoder9191 Without ngrok token, ngrok urls don't work. For cloudflared it is temporary issue, will be fixed automatically
