### ISSUE TITLE
Suggestion need custom or own port forwarding tools

### ISSUE THREAD

**Issue by kali64amd** [KasRoudra/MaxPhisher#56]
Can we custom port forward option??? 

because cloud flare is blocking this script as phishing link.  

And it will complete Tool

**Comment by KasRoudra** [comment]
@kali64amd If you have any custom port forwarding tool, start that at port 8080. Then the link will work with MaxPhisher. Currently, there is no service good enough to be added in maxphisher

**Comment by kali64amd** [comment]
ok!!
