### ISSUE TITLE
Missing selection for "s" input in main menu

### ISSUE THREAD

**Issue by ErSeraph** [KasRoudra/MaxPhisher#6]
Im learning a lot thanks to this project, I love it.
I was wondering by the way that, by decoding this line
https://github.com/KasRoudra/MaxPhisher/blob/629fd8328b9e98e87401e17ac82b3ae93e218aa3/maxphisher.py#L869
there is a call for a method "saved()" by pressing "s" in the main menu, but the selection is not showed while executing maxphisher.py

Why?

**Comment by KasRoudra** [comment]
@ErSeraph Your answer is within the code. The `saved` will appear if the target file contains some data

**Comment by ErSeraph** [comment]
Pressing "s" I can see all my tests with my IPs, but the hint [s] is not showing
![image](https://user-images.githubusercontent.com/30057980/195312416-a44eeef0-2584-4b7b-ace0-edb96f4707e4.png)
![image](https://user-images.githubusercontent.com/30057980/195313106-ac447a53-71e7-4d50-9520-461d6442d76a.png)

**Comment by KasRoudra** [comment]
@ErSeraph Although you can access it from main menu, this option is mainly for `Login` section(It contains login data only). If you choose 1 and go to login menu, you will find that the `Saved` option appears
