### ISSUE TITLE
I need help please!

### ISSUE THREAD

**Issue by Useranon999** [KasRoudra/MaxPhisher#60]
Hello, I need help with the tool, when I give the command "python3 maxphisher.py" the following message appears

File "/data/data/com.termux/files/home/maxphisher.py", line 958
    if has_files == "y":
IndentationError: unexpected indent

I've always used the tool normally, a few days ago this error appeared and I couldn't solve it until now
Thanks in advance.

**Comment by KasRoudra** [comment]
@Useranon999 Run `git pull`

**Comment by Useranon999** [comment]
> 

How?(I apologize for the inconvenience)
