### ISSUE TITLE
Could be simpler

### ISSUE THREAD

**Issue by busterbeam** [KasRoudra/MaxPhisher#63]
https://github.com/KasRoudra/MaxPhisher/blob/1d4e75c3cd7377af4b232f0ae55e4cc901eea5f7/maxphisher.py#L518-L541

Instead try this

```python
headers = {
	"user-agent": "Mozilla/5.0 (Linux; Android 8.1.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36", 
	"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*[inserted by cython to avoid comment closer]/[inserted by cython to avoid comment start]*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
	"accept-language": "en-GB,en-US;q=0.9,en;q=0.8"}
if "facebook" in url:
	headers.update({
		"upgrade-insecure-requests": "1",
		"dnt": "1",
		"content-type": "application/x-www-form-url-encoded",
		"origin": "https://m.facebook.com",
		"referer": "https://m.facebook.com/",
		"sec-fetch-site": "same-origin",
		"sec-fetch-mode": "cors",
		"sec-fetch-user": "empty",
		"sec-fetch-dest": "document",
		"sec-ch-ua-platform": "Android",
		"accept-encoding": "gzip, deflate br"})
```

**Comment by KasRoudra** [comment]
@busterbeam Does [this](https://github.com/KasRoudra/MaxPhisher/commit/9f711dd06ba1031928d0f88aea43244972987bf3) fix all of your issues? Do you have any more suggestion?

**Comment by Kaswan2793** [comment]
Sorry bro

**Comment by Kaswan2793** [comment]
pkg install openssl tray

**Comment by busterbeam** [comment]
> @busterbeam Does [this](https://github.com/KasRoudra/MaxPhisher/commit/9f711dd06ba1031928d0f88aea43244972987bf3) fix all of your issues? Do you have any more suggestion?

Sadly no, I have commented [here](https://github.com/KasRoudra/MaxPhisher/commit/9f711dd06ba1031928d0f88aea43244972987bf3#r113248710) to explain what readability improvement your missing

**Comment by KasRoudra** [comment]
@busterbeam Have a look at the latest [commit](https://github.com/KasRoudra/MaxPhisher/commit/9b3480990e7b343b99b93be7d3c27fa11b955b07)
