### ISSUE TITLE
Previous php still running! Please restart terminal and try again

### ISSUE THREAD

**Issue by FirzzyFunTWO** [KasRoudra/MaxPhisher#69]
Using php8.x.cli on Ubuntu 22.04
doing installation as guide. installation via `sudo pip3 install maxphisher`. after execute  `sudo maxphisher`
then error `[!] Previous php still running! Please restart terminal and try again`

**Any solution?.  ALREDY TRIED RESTARTING PHP SERVICES!**

**Comment by KasRoudra** [comment]
@FirzzyFunTWO Restarting php services won't work. You should **CLOSE** all php services

**Comment by kklin580** [comment]
> @FirzzyFunTWO Restarting php services won't work. You should **CLOSE** all php services

how would you do that hypothetically speaking? experiencing the same issues here

**Comment by KasRoudra** [comment]
@kklin580 Grab the pids by `pidof php`. Then run `sudo kill -9 <pid>`. Replace pid with actual one
