### ISSUE TITLE
Don't code like that!!

### ISSUE THREAD

**Issue by busterbeam** [KasRoudra/MaxPhisher#7]
https://github.com/KasRoudra/MaxPhisher/blob/629fd8328b9e98e87401e17ac82b3ae93e218aa3/maxphisher.py#L93

I can understand that you want it to work without imports and such, but don't do this!!!

**Comment by KasRoudra** [comment]
@busterbeam Thanks for your suggestion. But everything has a specific purpose in code and I am not changing that

**Comment by busterbeam** [comment]
Well if any one is wondering what it does, does this.

```
from os import popen, mknod, mkdir, listdir, system, getenv, replace, rename, remove, kill
from os.path import isfile, isdir, basename, dirname, abspath, join
from shutil import copyfile, copy2, copytree, rmtree, get_terminal_size
from glob import glob
from time import time, ctime
from signal import SIGTERM, SIGKILL, SIGINT
from subprocess import run, call, Popen, PIPE, DEVNULL, STDOUT
from platform import uname
from sys import stdout, version_info
from socket import setdefaulttimeout, socket, AF_INET as inet, SOCK_STREAM as stream
from http.client import HTTPSConnection
from time import sleep
from re import search, sub
from json import loads as parse, dumps as stringify
from smtplib import SMTP_SSL as smtp
from importlib import import_module as eximport
from zipfile import ZipFile
from tarfile import open as taropen
from argparse import ArgumentParser
```

also using your "compression" method increases the character count by 88%

**Comment by KasRoudra** [comment]
@busterbeam It wasn't compression either. Rather it was encoding multiple times, if I wished I could've increased it more

**Comment by busterbeam** [comment]
To be more clear you put it through cycles of encoding and compression.  that would be more precise.  for compression I suggest you use `lzma.compress` with `9|PRESET_EXTREME` so that it is more dense.  or in your more colourful language `__import__("\x6C\x7A\x6D\x61").compress(...)`

**Comment by busterbeam** [comment]
were you trying to encrypt?

**Comment by KasRoudra** [comment]
@busterbeam Yeap it's encoded so that script-kiddies can't steal it. I do not agree to keep it 100% open source. Current one it perfect

**Comment by busterbeam** [comment]
> @busterbeam Yeap it's encoded so that script-kiddies can't steal it. I do not agree to keep it 100% open source.

There are much better ways to do this..

**Comment by KasRoudra** [comment]
@busterbeam What's that?

**Comment by busterbeam** [comment]
Alright so you probably should read over the differences and such of coding (encoding/decoding), compression/decompression and crypt (encrypt/decrypt).

 - [base64](https://docs.python.org/3/library/base64.html)
 - [compression and archiving](https://docs.python.org/3/library/archiving.html)
 - [cryptographic](https://docs.python.org/3/library/crypto.html)

"coding" is a lot more complicated than just `base64`, technically you could use `pickle` and many other modules to represent data differently but its not hard to "crack" that stuff

"compression" is just helpful to keep the size down as you probably know, but nesting compression won't get any where.

"crypt"-ooo is what you want look into [Polymorphic Code](https://en.wikipedia.org/wiki/Polymorphic_code), the idea, you want is hashing various functions states, memory states, etc... provides the key to unlock other parts, but just keep it to your `main` function, that is your `main` function should/could be obfuscated, with encryption and in that function you run more memory checks to continue execution.

I would fiddle with this code more but looking at your de-obfuscated code is still quite painful and looks mashed together, you could still more optimizations here.

**Comment by KasRoudra** [comment]
@busterbeam I don't need compression nor cryptography. All I need is base64 encoding to save a my code from script-kiddies but keep the code decodable for real programmers so that if they can check if anything is malicious. Otherwise I could've encoded in marshal or in bytecode or even in cpython. But the encoding is against script kiddies only, so there is this simple base64 encoding with zlib compression.

**Comment by busterbeam** [comment]
You say
> I don't need compression

then say
> with zlib compression

Which is it? I think you mean to say maybe your not to concerned by compression, `zlib` is good but I will keep on suggesting `lzma` much more performant.

>  they can check 

I will admit not properly discussing compiling, but as you said and I could see what you were attemping, you wanted to maintain the plain text.  So yeah, I'm not suggesting you compile your code and lose value symbols, comments and literal representations.

hence I suggest encryption
> "crypt"-ooo is what you want look into [Polymorphic Code](https://en.wikipedia.org/wiki/Polymorphic_code)

This maintains your plain text readability but if a script kiddie modifies one character in your script it won't decrypt as the script will have an incorrect `hash`.  One of the checks you do is if your banner is modified, instead of storing your banner twice why not have a hash of it to compare it with, this seems a less script kiddie way to protect your script.

**Comment by KasRoudra** [comment]
@busterbeam I had that checking earlier. All the codes were open source except one expression where it checked for my name in banner. Only that expression was encoded into one line. You know what happened later? A script kiddie just deleted that line and keep stealing. Hence I had to encode more functions so that if he deletes, it won't work. Current one is safe enough against script kiddies, I'll have a look at `lzma` too. An encryption isn't necessary either, I want to keep this decodable for real programmers.

**Comment by busterbeam** [comment]
My suggestion of hashing your banner for comparison isn't to be left in a decoded portion of your script, but instead allows for something more confusing for script kiddies (not unlike yourself) to read but also allows for better performance 

Encrypt is still decryptable (decodable) your program will still need to contain the decryption key, you can just be really smart use the scripts hash as a key.  I would still be able to crack it.

Combining both of the ideas above you could essentially use a hash of the banner string to decrypt portions of your code.

If they want to change the banner they will need to hash their banner and then use that hash in re-encryption of code

**Comment by KasRoudra** [comment]
@busterbeam I got your point. I've to encrypt some functions with the hash of banner. The key won't be hard-coded but will be generated on each execution hashing the banner. If banner changes the hash(encryption key) will also change and the decrypt will fail. I am going to give it a try today

**Comment by busterbeam** [comment]
this can close now.  after commit [acfa892ace6b32f4f555ed6fdd34be3905717486](https://github.com/KasRoudra/MaxPhisher/commit/acfa892ace6b32f4f555ed6fdd34be3905717486).  The `lambda` statements were removed.

**Comment by TKMX-NC-TKMX** [comment]
Oh shit!
