### ISSUE TITLE
Feature to use custom web pages for Picture Phishing

### ISSUE THREAD

**Issue by hellofathul** [KasRoudra/MaxPhisher#74]
Is it possible for me to modify the original webpage of party for the camera phishing site, so I can design a new UI for it so it doesnt look  so suspicious to allow webcam? I'm planning to make like a profile page so when the user clicks on take picture to set their profile picture, they can allow to open their webcam without getting suspicious

**Comment by KasRoudra** [comment]
@hellofathul It's quite complex to configure new sites in maxphisher. However, it's possible. You may start designing the ui and then send me the html, css files. Then I'll do the rest
