### ISSUE TITLE
Helppp me

### ISSUE THREAD

**Issue by JohnLenoiser** [KasRoudra/MaxPhisher#86]
![IMG_20230817_190259](https://github.com/KasRoudra/MaxPhisher/assets/142509511/0da6ce98-6894-449b-bcff-98f5d7b5915e)
Help me

**Comment by LuckyDucky3607** [comment]
try `python3 -m pip install -r files/requirements.txt`

**Comment by JohnLenoiser** [comment]
thanks @LuckyDucky3607
