### ISSUE TITLE
custom hosting

### ISSUE THREAD

**Issue by RootFungus** [KasRoudra/MaxPhisher#87]
Im trying to host a website its juts one file index.html and its hosting some different file from another directory

**Comment by KasRoudra** [comment]
@RootFungus How is this relevant to this repo?

**Comment by RootFungus** [comment]
im trying to do it with maxphisher using custom option

**Comment by RootFungus** [comment]
> @RootFungus How is this relevant to this repo?

im trying to do it with maxphisher using custom option

**Comment by KasRoudra** [comment]
@RootFungus Send screenshot of your target folder and screenshot of your input in 78 option
