### ISSUE TITLE
Discord webhook

### ISSUE THREAD

**Issue by juniardoss** [KasRoudra/MaxPhisher#89]
Can i connect this phis to discord webhook ???

**Comment by KasRoudra** [comment]
@juniardoss Not yet. You may receive the data to gmail at most

**Comment by juniardoss** [comment]
> @juniardoss Not yet. You may receive the data to gmail at most

how to receive data to gmail ???

**Comment by KasRoudra** [comment]
@juniardoss In gmail, enable 2FA and create an app password. Then edit `files/email.json` with your sender, receiver and password

**Comment by juniardoss** [comment]
> @juniardoss In gmail, enable 2FA and create an app password. Then edit `files/email.json` with your sender, receiver and password

thanks yall
