### ISSUE TITLE
Phishing link is capturing Ip but not redirecting into the website 

### ISSUE THREAD

**Issue by UnkownPlayerX000** [KasRoudra/MaxPhisher#91]
Hello I installed maxphisher on termux using this command `wget https://raw.githubusercontent.com/KasRoudra/MaxPhisher/main/maxphisher.py && python3 maxphisher.py` I installed the dependencies before hand after that it did it things it asked me for a loclx token I answered no I then entered 06 for the ip tracker put in the redirecting link then I enabled Hotspot then i made a custom link when I paste the link into brave it the tool captures the ip but the link doesn't redirect me to the website that I wanted here is what appears on my browser ![Screenshot_20230831-154442_Brave.jpg](https://github.com/KasRoudra/MaxPhisher/assets/118047020/b3522167-c1ef-4b21-8180-9d12497ad6d3)
And I am left with this link `https://aware-surplus-keywords-bs.trycloudflare.com/`
I think there Is a problem with the tool 
Also when I put in the loclx access token and when I make a custom link the link doesn't work neither it captures an ip I don't know why

**Comment by KasRoudra** [comment]
@UnkownPlayerX000 It's not any problem of tool. This issue may refer to cloudflared repo instead. Whatever, how many times have you face this issue? Does this happen for every option?

**Comment by UnkownPlayerX000** [comment]
> @UnkownPlayerX000 It's not any problem of tool. This issue may refer to cloudflared repo instead. Whatever, how many times have you faced this issue? Does this happen for every option?

I have only been using the 06 option I haven checked out any of the other ones I have faced this issue about 3 or 4 days now on my pc it used to work fine and I could grab ppl ip
