### ISSUE TITLE
Templates.json issue 

### ISSUE THREAD

**Issue by cleitin28838383** [KasRoudra/MaxPhisher#94]
Yo man my error with templates continue

Templates.json and this error appears

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libtalloc
Suggested packages:
  proot-distro
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)
E: Method https has died unexpectedly!
E: Sub-process https returned an error code (1)
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly

[•] Downloading website files....
Cloning into '/data/data/com.termux/files/home/.maxsites'...
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/git-core/git-remote-https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)

**Comment by KasRoudra** [comment]
@cleitin28838383 Entirely an issue of your termux. Delete it and install latest termux from fdroid/github
