### ISSUE TITLE
Timed out error

### ISSUE THREAD

**Issue by Pain0564** [KasRoudra/MaxPhisher#95]
![IMG-20230906-WA0001](https://github.com/KasRoudra/MaxPhisher/assets/144221143/45d126bb-8168-474c-bf23-78f94b7ae99a)

It keeps sending this after using, 
python3 maxphisher.py

And on termux, its not installing the requirements
![Screenshot_2023_0906_142930](https://github.com/KasRoudra/MaxPhisher/assets/144221143/47e5de99-8deb-47e3-8199-9d4b558786c2)

**Comment by KasRoudra** [comment]
@Pain0564 From where have you downloaded termux?

**Comment by Pain0564** [comment]
> 

From here, 

https://f-droid.org/en/packages/com.termux/

**Comment by Pain0564** [comment]
> @Pain0564 From where have you downloaded termux?

From here, https://f-droid.org/en/packages/com.termux/

**Comment by KasRoudra** [comment]
@Pain0564 Run `pip3 install rich requests beautifulsoup4`

**Comment by Pain0564** [comment]
It's working now
