### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Matt0yt** [KasRoudra/MaxPhisher#96]
C:\Users\matt0\MaxPhisher>python3 maxphisher.py
Traceback (most recent call last):
  File "C:\Users\matt0\MaxPhisher\maxphisher.py", line 49, in <module>
    from os import (
ImportError: cannot import name 'mknod' from 'os' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\os.py)

**Comment by KasRoudra** [comment]
Not supported on windows

https://github.com/KasRoudra/MaxPhisher#support
