### ISSUE TITLE
Installing requests Defaulting to user installation because normal site-packages is not writeable

### ISSUE THREAD

**Issue by P4BLO95** [KasRoudra/MaxPhisher#97]
wget https://raw.githubusercontent.com/KasRoudra/MaxPhisher/main/maxphisher.py && python3 maxphisher.py
--2023-09-14 20:52:13--  https://raw.githubusercontent.com/KasRoudra/MaxPhisher/main/maxphisher.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55503 (54K) [text/plain]
Saving to: 'maxphisher.py.2'

maxphisher.py.2                          100%[================================================================================>]  54.20K  --.-KB/s    in 0.008s  

2023-09-14 20:52:13 (6.80 MB/s) - 'maxphisher.py.2' saved [55503/55503]

Installing requests
Defaulting to user installation because normal site-packages is not writeable

how to fix this one?

**Comment by KasRoudra** [comment]
@P4BLO95 It's not any error and no fix is required

**Comment by P4BLO95** [comment]
i cant run it

**Comment by KasRoudra** [comment]
@P4BLO95 Send full screenshot
